# Generated by Django 4.2 on 2023-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('fulfilled', 'fulfilled'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
