# Generated by Django 4.2 on 2024-01-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parenttwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrentwo', to='store.category'),
        ),
    ]
